[workspace]
resolver = "2"
members = ["crates/valang", "crates/valang-runtime", "crates/valang-package", "crates/valang-wasm", "crates/valang-web", "crates/valang-verify"]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/vaulet-id/val"
license = "Apache-2.0"

[workspace.dependencies]
valang = { path = "crates/valang" }
